### ISSUE TITLE
Error with kraken get default

### ISSUE THREAD

**Issue by lunactic** [mittagessen/kraken-models#1]
When trying to get the default model I receive the following error: 

```
/data # kraken get default
Retrieving model	⣽Traceback (most recent call last):
  File "/usr/bin/kraken", line 10, in <module>
    sys.exit(cli())
  File "/usr/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1086, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/kraken/kraken.py", line 280, in get
    partial(spin, 'Retrieving model'))
  File "/usr/lib/python2.7/site-packages/kraken/repo.py", line 60, in get_model
    desc = json.loads(raw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting ',' delimiter: line 7 column 1095 (char 1254)
```

Any ideas on how to get around that?

**Comment by mittagessen** [comment]
There was a syntax error in the JSON metadata file. It's fixed now.

**Comment by lunactic** [comment]
Perfect!
Thanks a lot
