### ISSUE TITLE
Kraken can't access the model repository return 'API rate limit error'

### ISSUE THREAD

**Issue by colibrisson** [mittagessen/kraken-models#3]
Just ran `kraken get default` after installing and when I tried to download another model a couple of minutes after I got the following error:
```
Retrieving model .[0.4658] No 'object' field in repo head API response. 
Traceback (most recent call last):
  File "/home/colin/anaconda3/envs/kraken/bin/kraken", line 11, in <module>
    sys.exit(cli())
  File "/home/colin/.local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/colin/.local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/colin/.local/lib/python3.6/site-packages/click/core.py", line 1163, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/home/colin/.local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/colin/.local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/colin/.local/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/colin/anaconda3/envs/kraken/lib/python3.6/site-packages/kraken/kraken.py", line 435, in get
    partial(message, '.', nl=False))
  File "/home/colin/anaconda3/envs/kraken/lib/python3.6/site-packages/kraken/repo.py", line 56, in get_model
    raise KrakenRepoException('{}: {}'.format(r.status_code, resp['message']))
kraken.lib.exceptions.KrakenRepoException: 403: API rate limit exceeded for 82.67.162.65. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
```

`kraken list` return the same error.

**Comment by dirkroorda** [comment]
Get a personal token from GitHub.
