### ISSUE TITLE
forward() missing 1 required positional argument: 'hidden' when using en-default.pronn

### ISSUE THREAD

**Issue by colibrisson** [mittagessen/kraken-models#4]
I tried to use en-default.pronn from the repository with the command `kraken -i Screenshot2.png screenshot.txt binarize segment ocr -m en-default.pronn ` but I got the following error :
```
Loading RNN default	✓
Traceback (most recent call last):
  File "/home/colin/anaconda3/envs/kraken/bin/kraken", line 11, in <module>
    sys.exit(cli())
  File "/home/colin/.local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/colin/.local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/colin/.local/lib/python3.6/site-packages/click/core.py", line 1164, in invoke
    return _process_result(rv)
  File "/home/colin/.local/lib/python3.6/site-packages/click/core.py", line 1102, in _process_result
    **ctx.params)
  File "/home/colin/.local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/colin/anaconda3/envs/kraken/lib/python3.6/site-packages/kraken/kraken.py", line 220, in process_pipeline
    task(base_image=base_image, input=input, output=output)
  File "/home/colin/anaconda3/envs/kraken/lib/python3.6/site-packages/kraken/kraken.py", line 157, in recognizer
    for pred in bar:
  File "/home/colin/.local/lib/python3.6/site-packages/click/_termui_impl.py", line 285, in generator
    for rv in self.iter:
  File "/home/colin/anaconda3/envs/kraken/lib/python3.6/site-packages/kraken/rpred.py", line 301, in rpred
    preds = network.predict(line)
  File "/home/colin/anaconda3/envs/kraken/lib/python3.6/site-packages/kraken/lib/models.py", line 81, in predict
    o = self.forward(line)
  File "/home/colin/anaconda3/envs/kraken/lib/python3.6/site-packages/kraken/lib/models.py", line 69, in forward
    o = self.nn.nn(line)
  File "/home/colin/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/colin/.local/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/colin/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/colin/anaconda3/envs/kraken/lib/python3.6/site-packages/kraken/lib/layers.py", line 350, in forward
    o, _ = self.layer(inputs)
  File "/home/colin/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() missing 1 required positional argument: 'hidden'
```

**Comment by ryanfb** [comment]
See kraken#118.
