### ISSUE TITLE
Kraken can't get default

### ISSUE THREAD

**Issue by alix-tz** [mittagessen/kraken-models#6]
Hello, 

When running `kraken get default` I have the following error:

```
kraken get default
Retrieving model .Traceback (most recent call last):
  File "/home/timeus/miniconda3/envs/kraken/bin/kraken", line 10, in <module>
    sys.exit(cli())
  File "/home/timeus/miniconda3/envs/kraken/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/timeus/miniconda3/envs/kraken/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/timeus/miniconda3/envs/kraken/lib/python3.6/site-packages/click/core.py", line 1163, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/home/timeus/miniconda3/envs/kraken/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/timeus/miniconda3/envs/kraken/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/timeus/miniconda3/envs/kraken/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/timeus/miniconda3/envs/kraken/lib/python3.6/site-packages/kraken/kraken.py", line 445, in get
    partial(message, '.', nl=False))
  File "/home/timeus/miniconda3/envs/kraken/lib/python3.6/site-packages/kraken/repo.py", line 116, in get_model
    logger.error('Found {} models when querying for id \'{}\''.format(model_id))
IndexError: tuple index out of range
```

On another note, `kraken list` doesn't return the usual list but this instead:
```
kraken list
Retrieving model list .✓
10.5281/zenodo.2577813 (pytorch) - A generalized model for English printed text

```

**Comment by hassan5544** [comment]
@alix-tz did you solve the problem
 I am facing a similar one that I cant add models to the Kraken the only language appear in the list is English
